# These are supported funding model platforms

github: kartolo
patreon: kartolo
custom: ['https://buymeacoff.ee/kartolo', 'https://www.paypal.me/kartolo', 'http://www.amazon.de/gp/registry/3NIXEA6OTWU84']
